<x-media-library.browser
    :folders="$folders"
    :media-items="$mediaItems"
    :library-stats="$this->libraryStats"
    :breadcrumbs="$this->breadcrumbs"
    :type-filter="$typeFilter"
    :view-mode="$viewMode"
    :sort-direction="$sortDirection"
    :current-folder-id="$currentFolderId"
    :select-mode="$selectMode"
    :selected-media-id="$selectedMediaId"
    :selected-media-details="$selectedMediaDetails"
/>
